export const topics = [
  "Generate a very interesting topic for a short blog post.",
  "Generate a very interesting topic for a short story.",
  "Generate a very interesting topic for a short article.",
  "Generate a title for a short story in a wonderland",
  "Generate a title about science fiction.",
  "Generate a mind-boggling topic about quantum physics.",
  "Generate a title about a fantasy world.",
  "Generate a title about a post-apocalyptic world.",
  "Generate a title about a world without humans.",
  "Generate a title about a world without animals.",
  "Generate a title about a world without plants.",
  "Generate a title about a world without water.",
  "Generate a title about a world without air.",
  "Generate a title about a world without gravity.",
  "Generate a title about a world without time.",
  "Generate a title about a world without space.",
  "Generate a title about a world without light.",
  "Generate a title about a world without darkness.",
  "Generate a title about a world without colors.",
  "Generate a title about a world without sound.",
  "Generate a title about a world without silence.",
  "Generate a title about a world without temperature.",
  "Generate a title about a world without movement.",
  "Generate a title about a world without life.",
  "Generate a title about a world without death.",
  "Generate a title about a world without birth.",
  "Generate a title about a world without change.",
  "Generate a title about a world without stability.",
  "Generate a title about a world without chaos.",
  "Generate a title about a world without order.",
  "Generate a title about a world without freedom.",
  "Generate a title that will make the reader think.",
  "Generate a title that will make the reader feel inspired.",
  "Generate a title that will make the reader feel motivated.",
  "Generate a title that will make the reader feel happy.",
  "Generate a title that will make the reader feel sad.",
  "Generate a title that will make the reader feel angry.",
  "Generate a title that will make the reader feel surprised.",
  "Generate a title that will make the reader feel confused.",
  "Generate a title that will make the reader feel curious.",
  "Generate a title that will make the reader feel excited.",
  "Generate a title that will make the reader feel relaxed.",
  "Generate an unconventional title for a short blog post.",
  "Generate an unconventional title for a short story.",
  "Generate an unconventional title for a short article.",
  "Generate a title about a world without love.",
  "Generate a title about a world without hate.",
  "Generate a title about a world without fear.",
  "Generate a title about a world without courage.",
  "Generate a title about a world without hope.",
  "Generate a title about a world without despair.",
  "Generate a title about a world without faith.",
  "Generate a title about a world without doubt.",
  "Generate a title about a world without trust.",
  "Generate a title about a world without betrayal.",
  "Generate a title about a world without loyalty.",
  "Generate a title about a world without honesty.",
  "Generate a title about a world without lies.",
  "Generate a title about a world without truth.",
  "Generate a title about a world without justice.",
  "Generate a title about a world without injustice.",
  "Generate a title about a world without freedom.",
  "Generate a title about a world without free will",
  "Generate a title about a world without fate.",
  "Generate a title about a world without destiny.",
  "Generate a title about a world without purpose.",
  "Generate a title about a world without meaning.",
  "Generate a title about a world without value.",
  "Generate a title about a world without worth.",
  "Generate a title about a world without beauty.",
  "Generate a title about a world without ugliness.",
  "Generate a title about a world without perfection.",
  "Generate a title about a world without imperfection.",
  "Generate a title about a world without order.",
  "Generate a title about a world without chaos.",
  "Generate a title about a world without life.",
  "Generate a title about a world without death.",
  "Generate a title about a world without birth.",
  "Generate a title about a world without change.",
  "Generate a title about a world without stability.",
  "Generate a quirky title for a short blog post.",
  "Generate a quirky title for a short story.",
  "Generate a quirky title for a short article.",
];

export const removeQuotes = (str: string) => {
  if (str.startsWith('"') && str.endsWith('"')) return str.slice(1, -1);
  return str;
};

export const getMinuteRead = (str: string) => {
  return Math.round(str.split(" ").length / 200);
};
